const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('flock', {
  createTerminal: (id, cols, rows, cwd) => ipcRenderer.invoke('pty-create', { id, cols, rows, cwd }),
  pickDirectory: () => ipcRenderer.invoke('pick-directory'),
  pathForFile: (file) => webUtils.getPathForFile(file),
  beep: () => ipcRenderer.send('beep'),
  focusWindow: () => ipcRenderer.send('focus-window'),
  sendInput: (id, data) => ipcRenderer.send('pty-input', { id, data }),
  resize: (id, cols, rows) => ipcRenderer.send('pty-resize', { id, cols, rows }),
  kill: (id) => ipcRenderer.send('pty-kill', { id }),
  onData: (handler) => ipcRenderer.on('pty-data', (_e, payload) => handler(payload)),
  onExit: (handler) => ipcRenderer.on('pty-exit', (_e, payload) => handler(payload)),
  onStats: (handler) => ipcRenderer.on('pty-stats', (_e, payload) => handler(payload)),
  onLocation: (handler) => ipcRenderer.on('pty-location', (_e, payload) => handler(payload)),
  getPrefs: () => ipcRenderer.invoke('get-prefs'),
  savePrefs: (prefs) => ipcRenderer.send('save-prefs', prefs),
  onFocusMode: (handler) => ipcRenderer.on('focus-mode', (_e, on) => handler(on)),
  onFullScreen: (handler) => ipcRenderer.on('fullscreen-changed', (_e, on) => handler(on)),
  onCopyPlain: (handler) => ipcRenderer.on('copy-plain', () => handler()),
  onFlushPrefs: (handler) => ipcRenderer.on('flush-prefs', () => handler()),
  onPrefsChanged: (handler) => ipcRenderer.on('prefs-changed', (_e, payload) => handler(payload)),
  onUpdateAvailable: (handler) => ipcRenderer.on('update-available', (_e, payload) => handler(payload)),
  onUpdateNone: (handler) => ipcRenderer.on('update-none', (_e, payload) => handler(payload)),
  onUpdateDownloaded: (handler) => ipcRenderer.on('update-downloaded', (_e, payload) => handler(payload)),
  installUpdate: () => ipcRenderer.send('install-update'),
  openUpdate: (url) => ipcRenderer.send('open-update', url),
});
